<?php
require_once("../connect.php");
mysqli_query($dbm,"UPDATE SOSTAV SET SOSTAV.CENA=(SELECT SKLAD.CENA FROM SKLAD WHERE SKLAD.PRODUKT=SOSTAV.PRODUKT) WHERE ");
mysqli_query($dbm,"UPDATE PRODUKCIYA SET SEBEST=(SELECT SUM(SUMMA) FROM SOSTAV)");

?>